#! /bin/sh

# nonportable echo
case `echo "testing\c"; echo 1,2,3`,`echo -n testing; echo 1,2,3` in
  *c*,-n*) ECHO_N= ECHO_C='
' ECHO_T='	' ;;
  *c*,*  ) ECHO_N=-n ECHO_C= ECHO_T= ;;
  *)      ECHO_N= ECHO_C='\c' ECHO_T= ;;
esac

# find out as much as we can about this system

echo "-----------"
echo "SYSTEM NAME"
echo "-----------"
echo
for prog in hostname "uname -n"; do
   x=`$prog 2>/dev/null | sed 1q`
   if test -n "$x"; then echo "$prog: $x";  fi
done 2>/dev/null

echo
echo "-----------"
echo "SYSTEM TYPE"
echo "-----------"
echo
for prog in "uname -a" "/usr/sbin/sizer -c"; do
   x=`$prog 2>/dev/null | sed 1q`
   if test -n "$x"; then echo "$prog: $x";  fi
done 2>/dev/null

# Hardware information
echo
echo "--------------------"
echo "HARDWARE INFORMATION"
echo "--------------------"
echo

# programs with short output
for prog in arch "arch -k" machine "uname -X" "/usr/sbin/sizer -c" vmstat sys; do
   x=`$prog 2>/dev/null`
   if test -n "$x"; then echo "$prog: $x";  fi
done 2>/dev/null

# programs with a more verbose output
for prog in hinv /usr/sbin/sysdef; do
  x=`$prog 2>/dev/null`
  if test -n "$x"; then 
    echo
    echo "$prog:"
    echo "$x"
    echo
  fi
done 2>/dev/null

for file in /proc/cpuinfo /proc/meminfo; do
  if test -r $file; then
    echo
    echo "$file:"
    cat $file
    echo
  fi
done 2>/dev/null


# Compilers
echo
echo "---------"
echo "COMPILERS"
echo "---------"
echo

for compiler in gcc g77 g++ cc CC f77 F77; do
    for flag in --version -v -V -version; do
       x=`$compiler $flag 2>&1` && (echo $ECHO_N "$compiler $flag: $ECHO_C"; echo "$x" | head -1)
    done
done 2>/dev/null

echo

# libraries